import { FooterContactType } from "@/types/footer/footerContact.type";
import { FooterTabItemType } from "@/types/footer/footerTabItemType.type";

export const tab1: FooterTabItemType[] = [
  { title: "Canmore", content: "Chỗ ở cho thuê phù hợp với thiên nhiên" },
  { title: "Benalmádena", content: "Nhà cho thuê" },
  { title: "Marbella", content: "Căn hộ cho thuê" },
  { title: "Mijas", content: "Nhà cho thuê" },
  { title: "Prescott", content: "Nhà cho thuê" },
  { title: "Scottsdale", content: "Căn hộ cao cấp cho thuê" },
  { title: "Tucson", content: "Căn hộ cho thuê" },
  { title: "Jasper", content: "Cabin cho thuê" },
  {
    title: "Mountain View",
    content: "Chỗ ở cho thuê phù hợp với thiên nhiên",
  },
  { title: "Devonport", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Mallacoota", content: "Nhà cho thuê trên bãi biển" },
  { title: "Ibiza", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Anaheim", content: "Chỗ ở cho thuê phù hợp với gia đình" },
  { title: "Monterey", content: "Căn hộ cho thuê" },
  { title: "Paso Robles", content: "Nhà cho thuê" },
  { title: "Santa Barbara", content: "Nhà cho thuê trên bãi biển" },
  { title: "Sonoma", content: "Nhà cho thuê" },
  { title: "Hiển thị thêm", content: "More" },
];

export const tab2: FooterTabItemType[] = [
  { title: "Phoenix", content: "Căn hộ cao cấp cho thuê" },
  { title: "Hot Springs", content: "Căn hộ cao cấp cho thuê" },
  { title: "Los Angeles", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "San Diego", content: "Chỗ ở cho thuê hướng biển" },
  { title: "San Francisco", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Barcelona", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Prague", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Washington", content: "Chỗ ở cho thuê phù hợp với thiên nhiên" },
  { title: "Keswick", content: "Cabin cho thuê" },
  { title: "London", content: "Chỗ ở cho thuê hướng biển" },
  { title: "Scarborough", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Sherwood Forest", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "York", content: "Cabin cho thuê" },
  { title: "Paris", content: "Căn hộ cao cấp cho thuê" },
  { title: "Rhodes", content: "Biệt thự cho thuê" },
  { title: "Nashville", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Dublin", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Hiển thị thêm", content: "More" },
];

export const tab3: FooterTabItemType[] = [
  { title: "Lake Martin", content: "Nhà cho thuê ven hồ" },
  { title: "Banff", content: "Nhà cho thuê" },
  { title: "Nerja", content: "Biệt thự cho thuê" },
  { title: "Greer", content: "Cabin cho thuê" },
  { title: "Lake Havasu City", content: "Nhà cho thuê" },
  { title: "Lake Powell", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "North Rim", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Payson", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Pinetop-Lakeside", content: "Cabin cho thuê" },
  { title: "Red Rock", content: "Cabin cho thuê" },
  { title: "Dinner Plain", content: "Chỗ ở cho thuê phù hợp với thiên nhiên" },
  { title: "Streaky Bay", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Emerald Lake", content: "Cabin cho thuê" },
  { title: "Vancouver Island", content: "Cabin cho thuê" },
  { title: "Victoria", content: "Chỗ ở cho thuê hướng biển" },
  { title: "Idyllwild-Pine Cove", content: "Nhà cho thuê" },
  { title: "Mammoth Lakes", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Hiển thị thêm", content: "More" },
];

export const tab4: FooterTabItemType[] = [
  { title: "Mentone", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Sedona", content: "Chỗ ở cho thuê có hồ bơi" },
  { title: "Helen", content: "Căn hộ cao cấp cho thuê" },
  { title: "Pine Mountain", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Stone Mountain", content: "Cabin cho thuê" },
  { title: "Island Park", content: "Nhà cho thuê" },
  { title: "Blue Mountains", content: "Biệt thự cho thuê" },
  { title: "Asheville", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Blowing Rock", content: "Cabin cho thuê" },
  { title: "Boone", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Hochatown", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Pigeon Forge", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Townsend", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Wears Valley", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Cabins", content: "Nhà nghỉ dưỡng cho thuê" },
];

export const tab5: FooterTabItemType[] = [
  { title: "Dauphin Island", content: "Chỗ ở cho thuê phù hợp với thú cưng" },
  { title: "Fort Morgan", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Gulf Shores", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Bruny Island", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Crescent Head", content: "Nhà cho thuê" },
  { title: "Gerringong", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Hamilton Island", content: "Nhà cho thuê" },
  { title: "Lancelin", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Melbourne Beach", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Moonta Bay", content: "Chỗ ở cho thuê hướng biển" },
  { title: "Ocean Grove", content: "Nhà nghỉ thôn dã cho thuê" },
  { title: "Majorca", content: "Chỗ ở cho thuê phù hợp với thú cưng" },
  { title: "Big Sur", content: "Cabin cho thuê" },
  { title: "Bodega Bay", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Cambria", content: "Cabin cho thuê" },
  { title: "Cayucos", content: "Nhà nghỉ dưỡng cho thuê" },
  { title: "Huntington Beach", content: "Căn hộ cho thuê" },
];

export const tab6: FooterTabItemType[] = [
  { title: "Hồ bơi tuyệt vời", content: "" },
  { title: "Bắc Cực", content: "" },
  { title: "Khu cắm trại", content: "" },
  { title: "Xe cắm trại", content: "" },
  { title: "Lâu đài", content: "" },
  { title: "Container", content: "" },
  { title: "Nông thôn", content: "" },
  { title: "Thiết kế", content: "" },
  { title: "Nhà dưới lòng đất", content: "" },
  { title: "Nông trại", content: "" },
  { title: "Công viên quốc gia", content: "" },
  { title: "Vườn nho", content: "" },
  { title: "Thật ấn tượng!", content: "" },
  { title: "Nhà nhỏ", content: "" },
  { title: "Tháp", content: "" },
  { title: "Cối xay gió", content: "" },
  { title: "Luxe", content: "" },
];

export const tab7: FooterTabItemType[] = [
  { title: "London", content: "Anh" },
  { title: "Paris", content: "Île-de-France" },
  { title: "New York", content: "New York" },
  { title: "Barcelona", content: "Catalonia" },
  { title: "İstanbul", content: "İstanbul" },
  { title: "Bali", content: "Indonesia" },
  { title: "Amsterdam", content: "North Holland" },
  { title: "Miami", content: "Florida" },
  { title: "Madrid", content: "Community of Madrid" },
  { title: "Los Angeles", content: "California" },
  { title: "Rome", content: "Lazio" },
  { title: "Lisbon", content: "Lisbon" },
  { title: "Tokyo", content: "Tokyo" },
  { title: "Vienna", content: "Vienna" },
  { title: "Athens", content: "Hy Lạp" },
  { title: "Prague", content: "Séc" },
  { title: "Orlando", content: "Florida" },
];

export const contacts: FooterContactType[] = [
  {
    title: "Hỗ trợ",
    contacts: [
      "Trung tâm trợ giúp",
      "AirCover",
      "Chống phân biệt đối xử",
      "Hỗ trợ người khuyết tật",
      "Các tùy chọn hủy",
      "Báo cáo lo ngại của khu dân cư",
    ],
  },
  {
    title: "Đón tiếp khách",
    contacts: [
      "Cho thuê nhà trên Airbnb",
      "AirCover cho Chủ nhà",
      "Tài nguyên về đón tiếp khách",
      "Diễn đàn cộng đồng",
      "Đón tiếp khách có trách nhiệm",
      "Tham gia khóa học miễn phí về công việc Đón tiếp khách",
    ],
  },
  {
    title: "Airbnb",
    contacts: [
      "Trang tin tức",
      "Tính năng mới",
      "Cơ hội nghề nghiệp",
      "Nhà đầu tư",
      "Chỗ ở khẩn cấp Airbnb.org",
    ],
  },
];
