import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const airbnbVF = localFont({
  src: "./fonts/AirbnbCerealVF.woff2",
  variable: "--font-airbnb-vf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${airbnbVF.className} text-[14px] text-custome-black-100`}
      >
        <AntdRegistry>
          <div className="w-full fixed top-0 left-0 right-0 bg-white z-[200]">
            <Header />
          </div>
          <div className="max-w-[1280px] mx-auto px-2 pt-[160px] pb-[50px]">
            {children}
          </div>
          <div className="w-full bg-custome-gray-100">
            <Footer />
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
