import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Providers } from "@/app/globalRedux/provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-custom text-[14px] text-custome-black-100`}>
        <Providers>
          <AntdRegistry>
            <div className="w-full">{children}</div>
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
